fail_fast: true
repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.0
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
  
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--check", "--skip-string-normalization"]
  
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint ./src
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        stages: [commit]
        language: system
        entry: pytest
        types: [python]
  